### ISSUE TITLE
Created an Asset (with false error message - but still works)

### ISSUE THREAD

**Issue by rfustino** [RileyGe/algo-wallet#2]
Created an Asset (with false error message – but it worked). 

Repro
Create Asset
partially fill in values to submit
get error that more info is required

Fill out all the fields, re-submit, still get message that some error occurred, but the asset was actually created)

**Comment by RileyGe** [comment]
fix this bug on [commit ](https://github.com/RileyGe/algo-wallet/commit/513a1f0a7c3561b42cef0903c827b12410fddf12).
